### ISSUE TITLE
Blank window when starting app.

### ISSUE THREAD

**Issue by Viperlotus** [tappi287/openvr_fsr_app#14]
Hello, I recently installed this program. However, I'm having an issue where, when I start it up (I run it as admin), a blank window appears and nothing else ever happens.  Here is a screenshot of how it looks like:
![OVR_FSR Issue](https://user-images.githubusercontent.com/2438212/133947343-1ba68d03-2509-4264-ba4a-8df41da3d52d.PNG)

**Comment by tappi287** [comment]
Hey, thanks for the report. There is no need to run this app as admin. Simply resize the window to force a re-draw. This is browser specific behaviour and I'm afraid I won't find the time to test this in all conditions in all browsers.
