### ISSUE TITLE
Custom game path

### ISSUE THREAD

**Issue by tatunts** [tappi287/openvr_fsr_app#2]
Hello again :)

A nice update for this project would be to add a custom path for games that are not automatically detected from the Steam library, so we could inject the DLL and better control its settings.

A great example, would be EmuVR, since it does not install from Steam and FSR helps A LOT.

Thank you!

**Comment by Adil3tr** [comment]
Seconding this.

**Comment by tappi287** [comment]
I also think this would be very useful but I'm not sure I'll find the time right now to add this.

**Comment by tatunts** [comment]
No worries! Thanks for the reply. Have a great day!

**Comment by Adil3tr** [comment]
Thanks!

**Comment by tappi287** [comment]
I had to implement some other features first(disk cache) to make sure this would work. Think I can implement this at the weekend.

**Comment by tappi287** [comment]
This was added with 0.5.0 see
[github.com/tappi287/openvr_fsr_app/releases/latest](github.com/tappi287/openvr_fsr_app/releases/latest)
