### ISSUE TITLE
NVIDIA Image Scaling Support

### ISSUE THREAD

**Issue by Adil3tr** [tappi287/openvr_fsr_app#20]
Fholger updated his solution to also support NVIDIA Image Scaling. Having that in the GUI as well would be really helpful.

**Comment by ASchneiderBR** [comment]
I was about to open an issue as well hahah nice!

**Comment by tappi287** [comment]
Thanks for the info. I'll check it out

Antonio Schneider ***@***.***> schrieb am Do., 18. Nov. 2021,
00:18:

**Comment by Adil3tr** [comment]
> Thanks for the info. I'll check it out

Thanks for adding this, but can you attach a portable release as well like with the other releases?

**Comment by tappi287** [comment]
Ah, right =] Can attach that tonight. It was a rapid release..

Adil3tr ***@***.***> schrieb am Do., 25. Nov. 2021, 02:57:

**Comment by tappi287** [comment]
https://github.com/tappi287/openvr_fsr_app/releases/download/0.6.0/OpenVR-FSR-App_0.6.0_win64_portable.7z

**Comment by Adil3tr** [comment]
Thanks!
