### ISSUE TITLE
could you intergrate Fixed Foveated rendering too please?

### ISSUE THREAD

**Issue by explogeek** [tappi287/openvr_fsr_app#23]
https://www.reddit.com/r/virtualreality/comments/rmhpp9/my_newest_vr_performance_mod_adds_fixed_foveated/
https://github.com/fholger/openvr_foveated/

**Comment by tappi287** [comment]
Yeah, sounds like a good idea but I'm not sure how much refactoring will be needed for that. I'll take a look

**Comment by Adil3tr** [comment]
Was about to suggest this as well. It would be really helpful and that one is more hit or miss so an easy way to quickly enable and disable it for lots of games would be great.

**Comment by tappi287** [comment]
I had not much time to test this if you guys could have a look:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.7.0
A quick test with cosmic trip with either FSR or Foveated mod. Something to test would be user added apps.

**Comment by tappi287** [comment]
Fixed some obvious bugs the refactoring introduced:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.7.2
Should be stable now.

**Comment by Adil3tr** [comment]
Seems to work for me, thanks! Small thing, when I click "installed," it filters to the ones with FSR enabled but doesn't include the ones with foveation enabled.

**Comment by tappi287** [comment]
> Seems to work for me, thanks! Small thing, when I click "installed," it filters to the ones with FSR enabled but doesn't include the ones with foveation enabled.

This is fixed now. Thanks for the hint!
