### ISSUE TITLE
Support for Contrast Adaptive Sharpening./Color Balance?

### ISSUE THREAD

**Issue by Adil3tr** [tappi287/openvr_fsr_app#25]
FHolger made this package: https://github.com/fholger/reshade/releases/tag/openvr_alpha2

It's a sharpening filter and, more importantly, a color rebalance for games that makes them look better on LCD displays. It's even more files than the other mods and support for installing this through the GUI would be really helpful. It's not quite the same but it would benefit a lot.

**Comment by tappi287** [comment]
I'm afraid this is out of scope of this project. While I'd find that useful too, there is a lot more file reading and editing involved when using reshade. Eg. my [rfactor 2 settings widget](https://github.com/tappi287/rf2_video_settings/blob/master/rf2settings/vrtoolkit.py) uses a ReShade extension for sharpening and color adjustments.

I'd personally recommend [VRToolKit](https://vrtoolkit.retrolux.de/gamelist.html) which is based on a more recent ReShade release and allows in-game settings adjustment aswell as advanced color corrections via LUT's
