### ISSUE TITLE
V0.8.1 Installation location only partly updated

### ISSUE THREAD

**Issue by TonyWhitley** [tappi287/openvr_fsr_app#30]
I moved my copy of AMS (1) to C:/Program Files (x86)/Steam/steamapps/common/Automobilista and rescanned.  The GUI shows the new location but when I try to install I get an error about the old location (which no longer exists):
_Error during OpenVRMod install/uninstall: [Errno 2] No such file or directory: 'C:\\Users\\tony_\\Documents\\SmallSSD\\games\\stea_

**Comment by TonyWhitley** [comment]
Looking in c:\Users\tony_\AppData\Local\openvr_fsr_app\steam_apps.json I see
"name": "Automobilista", "sizeGb": "34 GB", "path": "C:/Program Files (x86)/Steam/steamapps/common/Automobilista", "openVrDllPaths": ["C:/Program Files (x86)/Steam/steamapps/common/Automobilista/openvr_api.dll"], "openVrDllPathsSelected": ["C:/Users/tony_/Documents/SmallSSD/games/steamapps/common/Automobilista/openvr_api.dll"], "openVr": true, "SizeOnDisk": "36691199159", "appid": "431600"},

Using Visual Studio Code to view it but it can't cope very well with such a large file.

**Comment by TonyWhitley** [comment]
I edited **openVrDllPathsSelected** in steam_apps.json and it now installs the plugin.

**Comment by tappi287** [comment]
Hey Tony, thanks for the detailed analysis. I'll be able to fix this

**Comment by tappi287** [comment]
This is fixed with https://github.com/tappi287/openvr_fsr_app/releases/tag/0.8.3
