### ISSUE TITLE
Moving the Install of a game breaks gui

### ISSUE THREAD

**Issue by VictorBrek** [tappi287/openvr_fsr_app#31]
After moving a game from my C: Drive to my E: Drive it throws "Error writing OpenVRMod CFG file." when clicking the dropdown on the game, and I now have to edit the openvr_mod.cfg manually. let me know if there is anything else I could provide. Reupdating the library does not fix the issue.

**Comment by tappi287** [comment]
This is fixed in the latest release https://github.com/tappi287/openvr_fsr_app/releases/tag/0.8.4
