### ISSUE TITLE
Can't change Foveated Plugin directory.

### ISSUE THREAD

**Issue by ArsenicBismuth** [tappi287/openvr_fsr_app#33]
As the title suggest, you're currently only able to change the OpenVR FSR plugin dir, but not the Foveated plugin dir. As a result, if you run the app for the first time in dir Z then move it to X, you can't fix it other than modifying the app config file manually (which I don't know where) or not move the app at all.

**Comment by tappi287** [comment]
Ah, good observation. Btw. it would be in `%localappdata%\openvr_fsr_app\settings.json` `openvr_foveated_dir`
I'm thinking about dropping openvr_xy_mod support and moving forward to vrperfkit but am not sure how mature the new plugin is at this point

**Comment by tappi287** [comment]
github.com/tappi287/openvr_fsr_app/releases/latest
This should be fixed. Please re-open if it doesn't work
