### ISSUE TITLE
Add support for Holgers new vrperfkit....

### ISSUE THREAD

**Issue by nabel0** [tappi287/openvr_fsr_app#34]
From Holgers "openvr_fsr" github page:

NOTE: I am working on a new project that supercedes this mod. It supports the same upscaling methods as this mod, but in addition also works with the Oculus runtime and will eventually add additional performance enhancement tools. As a consequence, this project is in maintenance mode, and I encourage you to check out the new project: VR Performance Toolkit

--> https://github.com/fholger/vrperfkit

**Comment by tappi287** [comment]
THanks for the hint, this is in progress:
https://github.com/tappi287/openvr_fsr_app/commits/master

**Comment by nabel0** [comment]
Awesome...If you need a tester just ask ;)

**Comment by drowhunter** [comment]
was just about to ask for this very feature

**Comment by tappi287** [comment]
github.com/tappi287/openvr_fsr_app/releases/latest
Please report any issues (regarding the app). The only so far I could test was Cosmic Trip. All others failed to get hooked by the dll.

**Comment by drowhunter** [comment]
So i see the new button but it's greyed out ,  but the openvr buttons are enabled. How do i get the perfkit button to enable?

![image](https://user-images.githubusercontent.com/2817488/151035556-0f4bc517-105e-4d9e-8349-4bdac76c7f7e.png)

**Comment by tappi287** [comment]
Hey, I was trying to avoid a complete settings wipe in these 0.x versions. You will need to remove any custom apps from previous versions and add them again for them to be properly scanned for executables/vrperfkit install paths.

When we hit v1.x I'll rename the app to VR Mod App with a settings wipe.

**Comment by tappi287** [comment]
> So i see the new button but it's greyed out , but the openvr buttons are enabled. How do i get the perfkit button to enable?
> 
> ![image](https://user-images.githubusercontent.com/2817488/151035556-0f4bc517-105e-4d9e-8349-4bdac76c7f7e.png)

The app will re-scan your steam lib with every version. if you somehow canceled that the appropiate paths to install vrperfkit will not show up.
