### ISSUE TITLE
Feature Request : Update existing installations

### ISSUE THREAD

**Issue by drowhunter** [tappi287/openvr_fsr_app#35]
If you have installed the mod to games already and a new version comes out, there should be an option to update the dll for all of them.

Preferrably maintaining your existing settings.

**Comment by drowhunter** [comment]
would also be nice if you could display which version of the mod is installed to the game next to the title

**Comment by tappi287** [comment]
I won't trigger multiple file system activities from a single user interaction without a code signed executable. Please see https://github.com/tappi287/openvr_fsr_app/issues/6#issuecomment-899921609
