### ISSUE TITLE
Viveport support

### ISSUE THREAD

**Issue by drowhunter** [tappi287/openvr_fsr_app#36]
Would be nice if you could add support for multiple libraries.

Rather than specifically supporting Viveport.  You could add the ability to have the user choose to add more folders to be scanned.

This way I could add my Viveport folder and my Itch.io folder etc..

**Comment by tappi287** [comment]
You can add custom "User Apps" with the plus sign in the top left menu. I'll have a look into scanning arbitary directories

**Comment by drowhunter** [comment]
Yes this would be great

**Comment by tappi287** [comment]
Do these Viveport/Itch.io apps manage their own library folder like eg. EA's Origin, Uplay etc. and do you know if and where these locations are stored in the Windows registry? Typically something like HKCU\Software\EvilCorp\SomeKey or HKLocalMachine\ ...

**Comment by tappi287** [comment]
For now you can manually add it as a custom lib in the latest release.

**Comment by drowhunter** [comment]
I searched and could not find any registry entry for viveport app location.  

However I made this library a while back to scan my viveport folder for applications.  Feel free to use it if it helps

https://github.com/drowhunter/VivePortLibraryManager

returns an array of games found with their information
```
 {
    "Name": "Traffic Cop",
    "Url": "viveport.desktop://runapp/7a4a9c49-ede7-4672-8dfe-a3d7b2f8c755",
    "Thumbnail": "F:\\Viveport\\ViveApps\\7a4a9c\\Thumbnail-square.jpg",
    "AppKey": "vive.htc.7a4a9c49-ede7-4672-8dfe-a3d7b2f8c755",
    "LaunchType": "url",
    "Arguments": "-compositor",
    "ExePath": "F:\\Viveport\\ViveApps\\7a4a9c\\Traffic Cop.exe"
  }
```

**Comment by tappi287** [comment]
Thanks for the info! Hmm, I can not implement that then. If there is no way to auto detect the initial path and even if.. maintaining such an edge case will not be in my time budget.
