### ISSUE TITLE
Support for Oculus Software Library

### ISSUE THREAD

**Issue by nabel0** [tappi287/openvr_fsr_app#37]
Thank you so much for updating the app and support for the new "VrPerfKit".
The "VrPerfKit" supported runtime is not only "OpenVR" anymore. Oculus runtine is now also supported.
So it would be cool if you not only scan the steam library for games but also the Oculus game library.

**Comment by nabel0** [comment]
> Do you know if and where the path to that file directory is stored in the Windows registry? Typically something like HKCU\Software\EvilCorp\SomeKey or under HKLM...

For me it looks like this:
![Screenshot 2022-01-27 195045](https://user-images.githubusercontent.com/50377455/151424473-5322879f-d923-4765-88e5-6527209d4eab.jpg)

**Comment by CptAnonymou5** [comment]
How would we use this oculus kit for games in steam that use oculus sdk vs steam's or openvr?

**Comment by tappi287** [comment]
Thanks for the info, I'll see if I can implement a auto detect in the future. For now you can manually add it as a custom lib in the latest release.
