### ISSUE TITLE
Cannot install VrPerfKit from UI

### ISSUE THREAD

**Issue by ASchneiderBR** [tappi287/openvr_fsr_app#40]
Hello!

Sorry to bother you, I've searched here for an answer and could not find it.

I'm unable to install VrPerfKit mod from the UI, this option is greyed out, not sure why:

![image](https://user-images.githubusercontent.com/25224882/151377289-509a59bc-aba8-457a-b1ac-41f42f429310.png)

Any ideas what could be causing this?

Thanks!

**Comment by tappi287** [comment]
Hey, I was trying to avoid a complete settings wipe in these 0.x versions. You will need to remove any custom apps from previous versions and add them again for them to be properly scanned for executables/vrperfkit install paths.

When we hit v1.x I'll rename the app to VR Mod App with a settings wipe.

**Comment by ASchneiderBR** [comment]
Thanks! It worked.

I know it is hard to know what EXE to use, that is why it puts a copy of both files on each folder that it finds one...

![image](https://user-images.githubusercontent.com/25224882/151412961-09a0a8be-0046-4fe1-9ed3-96fc755b7cc3.png)

**Comment by tappi287** [comment]
That why this Install Location area is there, so you can select the desired locations. Is it not obvious/intuitive that these blue switches are checkboxes to select the desired locations?
I could deselect them by default but I thought that users will then ask why the vrperfkit install button is greyed out :D

**Comment by ASchneiderBR** [comment]
> That why this Install Location area is there, so you can select the desired locations. Is it not obvious/intuitive that these blue switches are checkboxes to select the desired locations? I could deselect them by default but I thought that users will then ask why the vrperfkit install button is greyed out :D

I think this is a great idea, I've seen them and tried to only leave switched on the ones that makes sense, according to the VrPerKit documentation. I think it is safe to leave all on by default, since both files have small sizes.

Thanks a lot!
