### ISSUE TITLE
Multiple custom app libraries

### ISSUE THREAD

**Issue by ASchneiderBR** [tappi287/openvr_fsr_app#41]
Hello!

Thanks for the latest update, now it is a lot easier to manage our custom path game by setting their root folder instead of one by one :)

I was wondering: would it be possible to add multiple custom app libraries paths? For example, 3 separated SSDs, all with X:/Games but I cannot add more than one custom library at a time:

![image](https://user-images.githubusercontent.com/25224882/151703273-a8588164-ad3f-4118-b68b-811cee3a7052.png)

The moment I add another library, the previous gets removed.

![image](https://user-images.githubusercontent.com/25224882/151703321-bc17c1c6-aa60-410e-a7ac-7de759cc0261.png)

It seems that it would be possible by the numbering scheme you have created...

Thanks again, great work here!

**Comment by tappi287** [comment]
Ah, oversight, the hash was generated based on the folder name, which is fixed now. Please just re-download the current release

**Comment by ASchneiderBR** [comment]
Amazing! Working great now:

![image](https://user-images.githubusercontent.com/25224882/151706557-b845cff6-e165-4d2f-8578-57d023557cac.png)

Thanks again!
