### ISSUE TITLE
Unable to remove vrperfkit plugin

### ISSUE THREAD

**Issue by jacklul** [tappi287/openvr_fsr_app#42]
After updating app to v0.9.4 all install locations went to checked state and trying to uninstall the plugin ends up with an error:
```
Error during OpenVRMod install/uninstall: [WinError 2] The specified file could not be found: '\\Steam\\steamapps\\common\\Zero Caliber VR\\ZeroCaliber\\Binaries\\Win64\\dxgi.dll'
Error during OpenVRMod install/uninstall: [WinError 2] The specified file could not be found: '\\Steam\\steamapps\\common\\Zero Caliber VR\\Engine\\Binaries\\Win64\\dxgi.dll'
Error during OpenVRMod install/uninstall: [WinError 2] The specified file could not be found: '\\Steam\\steamapps\\common\\Zero Caliber VR\\Engine\\Extras\\Redist\\en-us\\dxgi.dll'
```

I had only the location with `ZeroCaliber-Win64-Shipping.exe` checked before and it's location didn't error out.

Install locations:
```
/Steam/steamapps/common/Zero Caliber VR/Engine/Binaries/ThirdParty/OpenVR/OpenVRv1_5_17/Win64/openvr_api.dll
/Steam/steamapps/common/Zero Caliber VR/ZeroCaliber.exe
/Steam/steamapps/common/Zero Caliber VR/Engine/Binaries/Win64/CrashReportClient.exe
/Steam/steamapps/common/Zero Caliber VR/Engine/Binaries/Win64/UnrealCEFSubProcess.exe
/Steam/steamapps/common/Zero Caliber VR/Engine/Extras/Redist/en-us/UE4PrereqSetup_x64.exe
/Steam/steamapps/common/Zero Caliber VR/ZeroCaliber/Binaries/Win64/ZeroCaliber-Win64-Shipping.exe
```

After this error happens the uninstallation in app does not complete, the only workaround is to place dummy dxgi.dll in all those locations and uninstall again.
I think it would be good idea to ignore such errors and switch app mod state to uninstalled instead of keeping it installed.

**Comment by tappi287** [comment]
Thanks for the detailed report! Fixed:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.5

**Comment by jacklul** [comment]
I think the tooltips for "plugin installed/uninstalled" are reversed now (no idea if this was like this before), it shows "uninstalled" when installing and vice versa

**Comment by tappi287** [comment]
Ah, thanks, just a front-end oddity.
