### ISSUE TITLE
Windows Defender detects VR Mod App v0.9.5 as PUS, possible false positive?

### ISSUE THREAD

**Issue by ninlilizi** [tappi287/openvr_fsr_app#43]
openvr_fsr_app.exe is detected as Win32/Uwamson.A!ml by Windows Defender.

Probably a false positive, but always prudent to let the uploader know to double-check in these cases.

**Comment by ninlilizi** [comment]
Virustotal.com scan results

https://www.virustotal.com/gui/file/2f1b940fd4721450d418ba4f65b5ff5617e8aaab191006ccfb8b6b7ec268ca8f?nocache=1

**Comment by tappi287** [comment]
https://github.com/tappi287/openvr_fsr_app/issues/6
