### ISSUE TITLE
Error during OpenVRMod install

### ISSUE THREAD

**Issue by ASchneiderBR** [tappi287/openvr_fsr_app#47]
Hello!

Sorry to bother you but I'm unable to update some of my custom library games by removing and installing it again with the latest DLLs. I get those error messages:

```
31.03.2022 11:17:06.862 6460-app_fn save_steam_lib INFO: Updating SteamApp disk cache.
31.03.2022 11:17:06.903 6460-app_fn scan_app_lib_fn DEBUG: Providing Front End with Steam Library [27]
31.03.2022 11:17:08.118 6460-app_fn load_steam_lib_fn DEBUG: Loaded 27 Steam Apps from disk.
31.03.2022 11:17:14.079 6460-base_mod _install_single ERROR: Error during OpenVRMod install/uninstall: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Games\\EmuVR_1.0.9\\Game Scanner\\dxgi.dll'
31.03.2022 11:17:14.079 6460-base_mod _install_single ERROR: Error during OpenVRMod install/uninstall: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Games\\EmuVR_1.0.9\\Games\\Scummvm\\Leisure Suit Larry 6 - Shape Up or Slip Out (CD DOS)\\dxgi.dll'
31.03.2022 11:17:14.079 6460-base_mod _install_single ERROR: Error during OpenVRMod install/uninstall: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Games\\EmuVR_1.0.9\\Retroarch\\dxgi.dll'
31.03.2022 11:17:14.080 6460-base_mod _install_single ERROR: Error during OpenVRMod install/uninstall: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Games\\EmuVR_1.0.9\\dxgi.dll'
31.03.2022 11:17:14.803 6460-app_fn save_steam_lib INFO: Updating SteamApp disk cache.
```

Sorry, they are in Brazilian Portuguese but they just mean `System could not find the specified file`.

I've tried "reinstalling" your app by removing all settings from appdata and so on, nothing seems to fix this.

Thank you!

**Comment by tappi287** [comment]
Hey Antonio, thanks for the report but I'm afraid I can't provide much help without looking on the machine there. This seems to be a strange setup where this Emu VR is a VR app itself and then has other VR child apps!? There might be some conflicts if the child apps and parent app are scanned thru. Maybe someone with a similar setup can help.

As a side note: I'm not sure why one would want to install these plugins to such apps anyway. These plugins are not a magic trick to gain anything good. More like a universal way to decrease image quality when applied without the proper configuration for a certain use case.

**Comment by ASchneiderBR** [comment]
Hello @tappi287! Thanks for the reply.

Those are emulators and games (PCVR as exe) that gets recognized in your app, here's a screenshot:

![image](https://user-images.githubusercontent.com/25224882/161430744-232230c3-4dc5-464c-9eb4-5bab605654d4.png)

I cannot uncheck any of those locations, nor uninstall/remove it.

I've just clicked install with the default settings.

This problem also happens with a native VR app:

https://user-images.githubusercontent.com/25224882/161430989-069d1944-6094-4954-a22e-9c9bcbbf0114.mp4

Note that both are custom added libraries:

![image](https://user-images.githubusercontent.com/25224882/161430974-87c35464-e259-4fd0-8e93-69fb83a78afe.png)

Thank you!

**Comment by ASchneiderBR** [comment]
Another suggestion is to ignore the steam library from a custom library folder. For example, in my case, I’ve added a couple of X:/games/ folders, those folders are also used for steam library locations so it finds “duplicates” for the already found steam library default locations. Thanks.

**Comment by tappi287** [comment]
Hey, thanks for all the info! I may find the time to look into it next week.

**Comment by tappi287** [comment]
The behaviour has changed for VRP plugin dll's that had been manually removed by users:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.8

**Comment by ASchneiderBR** [comment]
> The behaviour has changed for VRP plugin dll's that had been manually removed by users: https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.8

Hello! The problem is now fixed! Thanks a lot, great work!
