### ISSUE TITLE
App start fails without Edge and Chrome

### ISSUE THREAD

**Issue by Sho0Fly** [tappi287/openvr_fsr_app#5]
Get an error, "Fetal Error Detected" when trying to launch app for the first time. States "Failed to execute script openvr_fsr_app" and closes. Things I've tried are running in Windows 8 Mode, as administrator, and reinstalling and installing older versions. All seem to give this error.

![Capture](https://user-images.githubusercontent.com/3311690/128957450-9998cb3f-43f2-42dd-b9f7-ee65b438afd2.PNG)

Specs:
Windows 11 Pro
RTX 3090
Intel i7 10900K

**Comment by tappi287** [comment]
Hi, there is most likely some library missing. You could install https://gitforwindows.org do a right click in the app folder, choose _Git Bash here_ and enter: `./openvr_fsr_app.exe` and then copy the output here.
Also take a look at your AppData\Local\openvr_fsr_app\Logs if you can find a log file there.

**Comment by Doctor-blob** [comment]
For @tappi287 I think this is the issue https://www.youtube.com/watch?v=ZtBTrARHJps  python doesn't compile the icon and so you need to manually transfert the icon in the folder containing the .exe

**Comment by Sho0Fly** [comment]
Gotta say I'm a complete newbie at this sort of stuff so bare with me :)

Downloaded git for windows and did all the default stuff, seemed to download successfully. Tried inputting ./openvr_fsr_app.exe into Git Bash and got this:
![Capture](https://user-images.githubusercontent.com/3311690/129123942-a4b6b4ed-03dc-4c8b-8365-884757e8dc09.PNG)

Guessing this is a case of I'm doing something terrible wrong... so log files it is:
[openvr_fsr_app.log](https://github.com/tappi287/openvr_fsr_app/files/6972234/openvr_fsr_app.log)

**Comment by tappi287** [comment]
@Sho0Fly Ok, thanks for the log. Hmm, do you not have Microsoft Edge installed on your system? Try this release, it should open the app in whatever your default browser is: https://github.com/tappi287/openvr_fsr_app/releases/tag/0.2.3
The downside of this is: it will not have it's own app window. So if you want to close the app(the executable that is running in the background and doing the actual work) you need to close the browser tab of the app. If you close and re-open the browser the tab with the app will no longer work. You could get around this by either installing Chrome or M$ Edge(Chromium)/latest WIndows Updates as they have proper "App Modes".

@Doctor-blob Sorry mate, but searching for the "Script failed" error message will not get you anywhere. Please follow my instructions posted earlier to get a more meaningful error message.

**Comment by Sho0Fly** [comment]
@tappi287 Thanks for the fix, running V3.0 fixed all the issues and opens in firefox. I think the issue occurred when I disabled Microsoft Edge somehow in W10 and W11 just nuked it entirely (windows likes to run everything in their own software even if default is chrome or firefox).

Only issue now is V3.0 is treated as a Trojan Horse by Windows Defender (guess they don't like the edge work around haha), but I see another thread has been opened about that. But it seems it works now so thanks for the quick fix, @tappi287 !

**Comment by tappi287** [comment]
Should be fixed then.
