### ISSUE TITLE
I cant get rid of VRPerfKit properly from my vrchat 

### ISSUE THREAD

**Issue by MaxiKitti** [tappi287/openvr_fsr_app#56]
![Screenshot 2022-11-21 191247](https://user-images.githubusercontent.com/98273834/203319855-81f80409-4c0f-4a38-aa80-4e6ef16f2fe5.png)

**Comment by tappi287** [comment]
Try the latest release:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.9
