### ISSUE TITLE
cant run app at all. Reinstalled the app, canary, chrome, no luck. 'localhost" refused to connect

### ISSUE THREAD

**Issue by samfisherirl** [tappi287/openvr_fsr_app#57]
![image](https://user-images.githubusercontent.com/98753696/208246287-de47a539-1929-4917-9cf4-23270bf5c4fc.png)

**Comment by tappi287** [comment]
Can you take a look if you find a ..exception.log under `%localappdata%\openvr_fsr_app`? +please use netstat to find any other software on your machine listening at port 8144. This port is needed for the app to run.

**Comment by saharasarge** [comment]
Same issue, no exception log and netstat shows nothing occupying port 8144

**Comment by tappi287** [comment]
Latest release adds an exception for this:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.9

**Comment by tappi287** [comment]
You could also try this release with extra logging to help pin down the problem:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.91
and report back here:
https://github.com/tappi287/openvr_fsr_app/issues/60
THanks
