### ISSUE TITLE
Cant Launch Steam VR if patched. 

### ISSUE THREAD

**Issue by Orvis25** [tappi287/openvr_fsr_app#58]
As title says, if i patch FSR into the "SteamVR" program itself (Id number 250820) The program refuses to launch. 
I get the window that pop up saying its trying to launch, but it never does. As soon as i remove the patch, it works again. 

Any help here?

**Comment by Orvis25** [comment]
Is this project dead? 
Any help?

**Comment by tappi287** [comment]
I'm pretty sure the mod dll was not supposed to do this. Consult https://github.com/fholger/openvr_fsr for help.
