### ISSUE TITLE
Support a active fork

### ISSUE THREAD

**Issue by able-archer** [tappi287/openvr_fsr_app#59]
Hey, RavenSystem has forked vrperfkit and already added new features.
Would be great if you could incorporate those into your UI!

https://github.com/RavenSystem/VRPerfKit_RSF/tree/3.2

**Comment by tappi287** [comment]
Thanks for the hint! I'll take a look whenever I find the time.. which may not be soon, sorry.

**Comment by tappi287** [comment]
Check this release:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.9
