### ISSUE TITLE
SteamVR support

### ISSUE THREAD

**Issue by azumukupoe** [tappi287/openvr_fsr_app#7]
openvr_api.dll is located in Steam\steamapps\common\SteamVR\bin\win32 and Steam\steamapps\common\SteamVR\bin\win64 but they aren't detected by the app

**Comment by tappi287** [comment]
Why would you want to replace the system-wide dll with one that is known to only work with a few titles? What is the result you are trying to achieve?

**Comment by azumukupoe** [comment]
Oh, didn't know it was system wide
I just wanted FSR for the vr home

**Comment by tappi287** [comment]
Ok. I'm not sure how controller bindings, tracking etc is setup in detail across Steam VR but would not recommend messing with Steam VR home.
If you want to try that, you'd have to install that manually and I'd recommend reporting your results back to https://github.com/fholger/openvr_fsr/issues
If it is reported to work there by multiple users I would consider adding it in the future.
