### ISSUE TITLE
Two little improvements

### ISSUE THREAD

**Issue by jacklul** [tappi287/openvr_fsr_app#8]
1. Don't delete the config when uninstalling - so you don't have to re-do your config after you temporarily uninstalled it
2. When installing import defaults from `data/openvr_fsr/openvr_mod.cfg` file (or user's custom path) instead of setting 75% scale/sharpness.

Also for some games it copies the dll to extra location it shouldn't - example Pavlov VR:
```
/Steam/steamapps/common/PavlovVR/Engine/Binaries/ThirdParty/OpenVR/OpenVRv1_0_16/Win64/openvr_api.dll
/Steam/steamapps/common/PavlovVR/Pavlov/Plugins/SteamVRInput/Source/ThirdParty/OpenVRSDK/bin/win64/openvr_api.dll
```
I believe copying it to SteamVRInput folder might mess up tracking, there is a warning about it in https://github.com/fholger/openvr_fsr/ repository.

**Comment by tappi287** [comment]
Hi, thanks for your suggestions:
1. No. The app will remove all files it writes to the users steam dirs as a user would expect. However, the behaviour you're describing will be in the next release. It will cache the Steam lib scan results to disk, including previous FSR settings.
2. You're right, the default setting was not matching the default cfg. It will be at 0.77 from next release. Reading the cfg is not intended and would conflict with settings cached on disk.
3. The next release will let the user decide to which location he wants to install.

**Comment by tappi287** [comment]
This has been addressed with the latest release
